--- config/crowdsec-blocklist-mirror.yaml.orig	2023-07-31 20:11:53 UTC
+++ config/crowdsec-blocklist-mirror.yaml
@@ -2,6 +2,7 @@ config_version: v1.0
 crowdsec_config:
   lapi_key: ${API_KEY}
   lapi_url: ${CROWDSEC_LAPI_URL}
+  retry_initial_connect: true
   update_frequency: 10s
   include_scenarios_containing: []
   exclude_scenarios_containing: []
